name: Deploy to Orange Pi

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build step (example)
      run: echo "Build your project here"

    - name: Test step (example)
      run: echo "Run tests here"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2

    - name: Copy project files
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.PI_HOST }}
        username: ${{ secrets.PI_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 2222
        source: "."
        target: "/Documents/qBot"

    - name: Deploy application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PI_HOST }}
        username: ${{ secrets.PI_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 2222
        script: |
          cd /Documents/qBot
          docker-compose down
          docker-compose up -d --build
